[tool.poetry]
name = "dat"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.2"
pyspark = "^3.5.0"
click = "^8.1.3"
delta-spark = "^3.0.0"
rootpath = "^0.1.1"
pyarrow = "^10.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
isort = "^5.10.1"
pytest = "^7.1.2"
coverage = "^6.4.4"
autopep8 = "^1.7.0"
mypy = "^0.971"
bandit = "^1.7.4"
unify = "^0.5"
chispa = "^0.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
